export { default as userData } from './userData.json'
export { default as posts } from './postData.json'
export { default as dataLike } from './likeData.json'
export { default as dataComment } from './commentData.json'
export { default as dataPosts } from './postData.json'
export { default as dataGroup } from './groupsData.json'
